name: Run Jest tests

on:
  push:
    branches:
      - complete

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        node-version: ${{matrix.node-version}}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test

    - name: Send POST request with JSON body and display response
      run: |
        USERNAME="${{ github.actor }}"
        URL="https://f765-2601-48-c602-41a0-8442-540c-dc23-b416.ngrok-free.app/post-data"
        TITLE="Your Title"
        BODY="Your Body Content $USERNAME"

        RESPONSE=$(curl -s -X POST -H "Content-Type: application/json" \
          -d "{\"title\": \"$TITLE\", \"body\": \"$BODY\"}" \
          "$URL")

        echo "Response from server:"
        echo "$RESPONSE"

